spring.application.name=sms
spring.data.mongodb.uri=mongodb://localhost:27017/docdb

# ? SQL datasource disable (IMPORTANT)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB
